import {
  Baby,
  BookOpen,
  Bus,
  Car,
  CircleEllipsis,
  CreditCard,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  PiggyBank,
  Plane,
  ReceiptText,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Train,
  Utensils,
  WalletCards,
  Wifi,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/* eslint-disable react-refresh/only-export-components */

const icons: Record<string, LucideIcon> = {
  Baby,
  BookOpen,
  Bus,
  Car,
  CircleEllipsis,
  CreditCard,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  PiggyBank,
  Plane,
  ReceiptText,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Train,
  Utensils,
  WalletCards,
  Wifi,
  Wrench,
};

export function CategoryIcon({ name, className }: { name: string; className?: string }) {
  const Icon = icons[name] ?? CircleEllipsis;
  return <Icon className={className} aria-hidden="true" />;
}

export const iconOptions = [
  { name: "ShoppingBasket", label: "Продукты" },
  { name: "Utensils", label: "Кафе" },
  { name: "Home", label: "Дом" },
  { name: "Car", label: "Машина" },
  { name: "Fuel", label: "Топливо" },
  { name: "Bus", label: "Транспорт" },
  { name: "Train", label: "Поездки" },
  { name: "HeartPulse", label: "Здоровье" },
  { name: "ShoppingBag", label: "Покупки" },
  { name: "Plane", label: "Отпуск" },
  { name: "Shirt", label: "Одежда" },
  { name: "Gift", label: "Подарки" },
  { name: "Wifi", label: "Связь" },
  { name: "Smartphone", label: "Телефон" },
  { name: "Laptop", label: "Техника" },
  { name: "Gamepad2", label: "Развлечения" },
  { name: "Dumbbell", label: "Спорт" },
  { name: "BookOpen", label: "Обучение" },
  { name: "Baby", label: "Дети" },
  { name: "Wrench", label: "Ремонт" },
  { name: "ReceiptText", label: "Счета" },
  { name: "CreditCard", label: "Карта" },
  { name: "Landmark", label: "Банк" },
  { name: "WalletCards", label: "Доход" },
  { name: "PiggyBank", label: "Цель" },
  { name: "Sparkles", label: "Красота" },
  { name: "Heart", label: "Забота" },
  { name: "CircleEllipsis", label: "Другое" },
];
